version: "3.9"

services:
  db:
    image: mariadb:10.11.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_PASSWORD=root123
      - MYSQL_DATABASE=photo_gallery_api
      - MYSQL_USER=photo-gallery
    volumes:
      - db:/var/lib/mysql
    networks:
      - photo-gallery-api-network

  photo-gallery-api:
    image: gallery-api:latest
    restart: always
    depends_on:
      - db
    volumes:
      - photos:/code/photos
      - ./app/config/parameters.yml:/code/app/config/parameters.yml
    networks:
      - photo-gallery-api-network
    ports:
      - 8001:80

volumes:
  db:
  photos:

networks:
  photo-gallery-api-network:
