# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    access_decision_manager:
        strategy: unanimous

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_users:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/authenticate$
            stateless: true
            anonymous: ~

        public:
            pattern: ^/(album/(\d+|\d+/downloadToken|random|list|list/\d+))|(album/search/.*)|(photo/\d+(/(thumb|resized|cover))?)$
            stateless: true
            methods: [GET]
            anonymous: ~

        main:
            pattern: ^/
            stateless: true
            methods: [GET, POST, PUT, DELETE]
            guard:
                authenticators:
                    - app.jwt_authenticator
