# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.jwt_authenticator:
        class: AppBundle\Security\JWTAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "%secret%"]

    app.voter.album_voter:
        class: AppBundle\Security\AlbumVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.voter.photo_voter:
        class: AppBundle\Security\PhotoVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.voter.comment_voter:
        class: AppBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "%secret%"]

    app.command.add_user:
        class: AppBundle\Command\AddUserCommand
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@logger"]
        tags:
            - { name: console.command }

    app.command.delete_user:
        class: AppBundle\Command\DeleteUserCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        tags:
            - { name: console.command }

    app.listener.photo_listener:
        class: AppBundle\EventListener\PhotoListener
        arguments: ["%photo_upload_dir%"]
        tags:
            - { name: doctrine.orm.entity_listener }

    app.listener.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }