# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.jwt_authenticator:
        class: AppBundle\Security\JWTAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "%secret%"]

    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "%secret%"]
