# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.jwt_authenticator:
        class: AppBundle\Security\JWTAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "%secret%"]

# Voters
    app.voter.album_voter:
        class: AppBundle\Security\AlbumVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.voter.photo_voter:
        class: AppBundle\Security\PhotoVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.voter.comment_voter:
        class: AppBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

# Controllers
    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "%secret%"]

# Commands
    app.command.add_user:
        class: AppBundle\Command\AddUserCommand
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@logger"]
        tags:
            - { name: console.command }

    app.command.delete_user:
        class: AppBundle\Command\DeleteUserCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        tags:
            - { name: console.command }

    app.command.set_user_password:
        class: AppBundle\Command\SetUserPasswordCommand
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@logger"]
        tags:
            - { name: console.command }

    app.command.update_resized_photos:
        class: AppBundle\Command\UpdateResizedPhotosCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger", "%photo_upload_dir%", "@app.services.photo_resizer"]
        tags:
            - { name: console.command }

    app.command.update_cover_photos:
        class: AppBundle\Command\UpdateCoverPhotosCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger", "%photo_upload_dir%", "@app.services.photo_resizer"]
        tags:
            - { name: console.command }

    app.command.update_photos_color:
        class: AppBundle\Command\UpdatePhotoColorCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger", "%photo_upload_dir%", "@app.services.color_extractor"]
        tags:
            - { name: console.command }

    app.command.update_archives:
        class: AppBundle\Command\UpdateArchivesCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger", "%photo_upload_dir%"]
        tags:
            - { name: console.command }

# Listeners
    app.listener.photo_listener:
        class: AppBundle\EventListener\PhotoListener
        arguments: ["%photo_upload_dir%", "@app.services.photo_resizer", "@app.services.color_extractor"]
        tags:
            - { name: doctrine.orm.entity_listener }

    app.listener.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.listener.json_body_listener:
        class: AppBundle\EventListener\JsonBodyRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.listener.cors_request_listener:
        class: AppBundle\EventListener\CorsRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.listener.cors_response_listener:
        class: AppBundle\EventListener\CorsResponseListener
        arguments: ["%cors_allow_origin%"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }

# Services
    app.services.photo_resizer:
        class: AppBundle\Service\PhotoResizer\ImagickPhotoResizer

    app.services.color_extractor:
        class: AppBundle\Service\ColorExtractor\LeagueColorExtractor
